version: "3"
services:
  user-service:
    image: user-service-img
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service/app:/code/app
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://root:password@mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - userdb:/data/db

  order-service:
    image: order-service-img
    build:
      context: ./order-service
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./order-service:/orders
    ports:
      - 8081:8081
    environment:
      - MONGODB_URL=mongodb+srv://root:YxsVxuxe1gLVbtQ1@orders.0nuix17.mongodb.net/?retryWrites=true&w=majority
    stdin_open: true
    tty: true

volumes:
  userdb:
